swagger: '2.0'

info:
  version: "1.0.0"
  title: GcApiV1
  description: API para o Siga-GC

basePath: /sigagc/api/v1
schemes: [http,https]
consumes: [application/json,application/x-www-form-urlencoded]
produces: [application/json]

tags:
  - name: auth
    description: Autenticação
  - name: download
    description: Download
    
securityDefinitions:
  Basic:
    type: basic
  Bearer:
    type: apiKey
    name: Authorization
    in: header

################################################################################
#                                   Parameters                                 #
################################################################################
parameters:
  sigla:
    name: sigla
    in: path
    description: Sigla do mobil
    type: string
    required: true
  completo:
    name: completo
    in: query
    description: Informar true se deseja receber todos os arquivos juntados e anexos
    required: false
    type: boolean
  estampa:
    name: estampa
    in: query
    description: Informar true se deseja receber o PDF sem estampas
    required: false
    type: boolean
  volumes:
    name: volumes
    in: query
    description: Informar true se deseja receber uma compilação com todos os volumes de um processo
    required: false
    type: boolean
  pdf:
    name: pdf
    in: path
    description: Referência para o PDF que foi enviado previamente para o servidor
    type: string
    required: true
  jwt:
    name: jwt
    in: path
    description: JWT que referencia um artefato a ser baixado
    required: true
    type: string
  filename:
    name: filename
    in: path
    description: Nome do arquivo de um artefato a ser baixado
    required: true
    type: string
  disposition:
    name: disposition
    in: query
    description: Informar attachment se desejar receber como um download
    required: false
    type: string
  contenttype:
    name: contenttype
    in: query
    description: Informar o tipo de arquivo desejado, pode ser application/pdf ou text/html
    required: false
    type: string
  chave:
    name: chave
    in: path
    description: Chave que referencia um processo assíncrono
    required: true
    type: string


################################################################################
#                                           Paths                              #
################################################################################
paths:
  /autenticar:
    post:
      summary: Recebe login e senha e gera um token JWT para ser usado nos outros métodos da API
      tags: [auth]
      security:
        - Basic: []
      parameters: []
      responses:
        200:
          description: Successful response
          schema:
            type: object
            properties:
              token:
                type: string
                description: Token JWT
        500:
          description: Error ocurred
          schema:
            $ref: "#/definitions/Error"
  /documento/{sigla}/arquivo:
    get:
      summary: Inicia o processo de geração do PDF completo de um documento para visualização
      tags: [download]
      security:
        - Bearer: []
      parameters:
        - $ref: "#/parameters/contenttype"
        - $ref: "#/parameters/sigla"
        - $ref: "#/parameters/estampa"
        - $ref: "#/parameters/completo"
        - $ref: "#/parameters/volumes"
      responses:
        200:
          description: Successful response
          schema:
            type: object
            properties:
              uuid:
                type: string
                description: UUID que pode ser usado como chave para obter status da geração do PDF
              jwt:
                type: string
                description: JWT com as informações para download do PDF
        500:
          description: Error ocurred
          schema:
            $ref: "#/definitions/Error"

  /download/{jwt}/{filename}:
    get:
      summary: Faz o download de um artefato qualquer, baseado nas informações contidas em um JWT
      tags: [download]
      parameters:
        - $ref: "#/parameters/jwt"
        - $ref: "#/parameters/filename"
        - $ref: "#/parameters/disposition"
      responses:
        200:
          description: Successful response
          schema:
            type: file
          headers:
            Content-Type:
              type: string
              description: application/pdf
            Content-Disposition:
              type: string
              description: attachment
        500:
          description: Error ocurred
          schema:
            $ref: "#/definitions/Error"
            
  /status/{chave}:
    get:
      tags: [download]
      parameters:
        - $ref: "#/parameters/chave"
      summary: Obtem o status de uma operação assíncrona
      responses:
        200:
          description: Successful response
          schema:
            type: object
            properties:
              mensagem:
                type: string
                description: Mensagem
              indice:
                type: number
                description: Quantos passos já foram executados
              contador:
                type: number
                description: Número total de passos a serem executados
              bytes:
                type: number
                description: Tamanho total do payload até o momento
              errormsg:
                type: string
                description: Mensagem de erro se houver
              stacktrace:
                type: string
                description: Detalhamento do erro
        500:
          description: Error ocurred
          schema:
            $ref: "#/definitions/Error"


################################################################################
#                                     Definitions                              #
################################################################################
definitions:
  Status:
    type: object
    properties:
      mensagem:
        type: string
        description: Mensagem
      indice:
        type: number
        description: Quantos passos já foram executados
      contador:
        type: number
        description: Número total de passos a serem executados
      bytes:
        type: number
        description: Tamanho total do payload até o momento
      errormsg:
        type: string
        description: Mensagem de erro se houver
      stacktrace:
        type: string
        description: Detalhamento do erro

  Error:
    type: object
    properties:
      errormsg:
        type: string