solicitante:
  nome: "sigadoc"
  sobrenome: "DevOps"

homologacao:
  pre_aprovado: true
  restricao_horario_inicio: "07:00"
  restricao_horario_fim: "23:00"

producao:
  pre_aprovado: false
  restricao_horario_inicio: "22:00"
  restricao_horario_fim: "23:59"